<?php
return [
    'bsVersion' => '5.x',
    //'bsDependencyEnabled' => false,
    //'adminEmail' => 'admin@example.com',
    //'supportEmail' => 'support@example.com',
    //'senderEmail' => 'noreply@example.com',
    //'senderName' => 'Example.com mailer',
    'adminEmail' => 'admin@ticketing.hardcode.biz.id',
    'supportEmail' => 'admin@ticketing.hardcode.biz.id',
    'senderEmail' => 'admin@ticketing.hardcode.biz.id',
    'senderName' => 'itcketing mailer',
    'user.passwordResetTokenExpire' => 3600,
    'user.passwordMinLength' => 8,
    'objectclasses' => [
        'common\\models\\Contract',
        'common\\models\\Holiday',
        'common\\models\\Item',
        'common\\models\\actors\\User',
        'common\\models\\actors\\Administrator',
        'common\\models\\actors\\Engineer',
        'common\\models\\actors\\Customer',
        'common\\models\\actors\\Company',
        'common\\models\\actors\\Depot',
        'common\\models\\actors\\Store',
        'common\\models\\docs\\Document',
        'common\\models\\docs\\Image',
        'common\\models\\docs\\Inquiry',
        'common\\models\\docs\\Invoice',
        'common\\models\\docs\\WorkOrder',
        'common\\models\\tickets\\Ticket',
        'common\\models\\tickets\\actions\\Action',
        'common\\models\\tickets\\actions\\MetaAction',
        'common\\models\\tickets\\actions\\ConcreteAction',
        'common\\models\\tickets\\actions\\Assignment',
        'common\\models\\tickets\\actions\\Discretion',
        'common\\models\\tickets\\actions\\Recommendation',
        'common\\models\\tickets\\actions\\Open',
        'common\\models\\tickets\\actions\\Repair',
        'common\\models\\tickets\\actions\\closings\Closing',
        'common\\models\\tickets\\actions\\closings\Awaiting',
        'common\\models\\tickets\\actions\\closings\Duplicate',
        'common\\models\\tickets\\actions\\closings\NoProblem',
        'common\\models\\tickets\\actions\\closings\Normal',
        'frontend\\models\\GeneralManager',
        'frontend\\models\\StoreManager',
    ]
];
